[E 180222 18:53:11 torndb:103] Cannot connect to MySQL on 127.0.0.1
[W 180222 18:53:29 Passport:12] warning msg
[E 180222 18:53:29 Passport:13] error msg
[E 180222 19:01:48 torndb:103] Cannot connect to MySQL on 127.0.0.1
[D 180222 19:02:47 Passport:10] debug msg
[I 180222 19:02:47 Passport:11] info msg
[W 180222 19:02:47 Passport:12] warning msg
[E 180222 19:02:47 Passport:13] error msg
[I 180222 19:02:47 web:1946] 304 GET / (127.0.0.1) 4.65ms
[D 180222 19:06:44 Passport:10] debug msg
[I 180222 19:06:44 Passport:11] info msg
[W 180222 19:06:44 Passport:12] warning msg
[E 180222 19:06:44 Passport:13] error msg
[I 180222 19:06:44 web:1946] 304 GET / (127.0.0.1) 13.59ms
[D 180222 19:32:17 Passport:10] debug msg
[I 180222 19:32:17 Passport:11] info msg
[W 180222 19:32:17 Passport:12] warning msg
[E 180222 19:32:17 Passport:13] error msg
[I 180222 19:32:17 web:1946] 304 GET / (127.0.0.1) 7.80ms
[E 180222 22:05:40 torndb:103] Cannot connect to MySQL on 127.0.0.1
    Traceback (most recent call last):
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/torndb.py", line 100, in __init__
        self.reconnect()
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/torndb.py", line 117, in reconnect
        self._db = MySQLdb.connect(**self._db_args)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
        return Connection(*args, **kwargs)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
        super(Connection, self).__init__(*args, **kwargs2)
    OperationalError: (1049, "Unknown database 'ihome'")
[I 180222 22:06:23 autoreload:204] /home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py modified; restarting server
[E 180222 22:06:23 torndb:103] Cannot connect to MySQL on 127.0.0.1
    Traceback (most recent call last):
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/torndb.py", line 100, in __init__
        self.reconnect()
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/torndb.py", line 117, in reconnect
        self._db = MySQLdb.connect(**self._db_args)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
        return Connection(*args, **kwargs)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
        super(Connection, self).__init__(*args, **kwargs2)
    OperationalError: (1049, "Unknown database 'ihome'")
[E 180222 22:06:48 web:1524] Uncaught exception GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/api/imagecode?codeid=123&pcodeid=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'csrftoken=d5vkJOixfySy6Dz9acL0SDbTrjtFsjvX; sessionid=bivt4n2wqw6y97akihbbv258djo1j4ru', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py", line 23, in get
        name, text, image =captcha.generate_captcha()
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 219, in generate_captcha
        return self.captcha("")
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 205, in captcha
        image = self.text(image, self.fonts, drawings=['warp', 'rotate', 'offset'])
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 128, in text
        for size in font_sizes or (65, 70, 75)])
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 260, in truetype
        return FreeTypeFont(font, size, index, encoding, layout_engine)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 143, in __init__
        self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
    IOError: cannot open resource
[E 180222 22:06:48 web:1946] 500 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 52.01ms
[E 180222 22:08:35 web:1524] Uncaught exception GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/api/imagecode?codeid=123&pcodeid=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'csrftoken=d5vkJOixfySy6Dz9acL0SDbTrjtFsjvX; sessionid=bivt4n2wqw6y97akihbbv258djo1j4ru', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py", line 23, in get
        name, text, image =captcha.generate_captcha()
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 219, in generate_captcha
        return self.captcha("")
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 205, in captcha
        image = self.text(image, self.fonts, drawings=['warp', 'rotate', 'offset'])
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 128, in text
        for size in font_sizes or (65, 70, 75)])
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 260, in truetype
        return FreeTypeFont(font, size, index, encoding, layout_engine)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 143, in __init__
        self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
    IOError: cannot open resource
[E 180222 22:08:35 web:1946] 500 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 26.06ms
[E 180222 22:13:12 web:1524] Uncaught exception GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/api/imagecode?codeid=123&pcodeid=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'csrftoken=d5vkJOixfySy6Dz9acL0SDbTrjtFsjvX; sessionid=bivt4n2wqw6y97akihbbv258djo1j4ru', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py", line 23, in get
        name, text, image =captcha.generate_captcha()
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 219, in generate_captcha
        return self.captcha("")
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 205, in captcha
        image = self.text(image, self.fonts, drawings=['warp', 'rotate', 'offset'])
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 128, in text
        for size in font_sizes or (65, 70, 75)])
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 260, in truetype
        return FreeTypeFont(font, size, index, encoding, layout_engine)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 143, in __init__
        self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
    IOError: cannot open resource
[E 180222 22:13:12 web:1946] 500 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 42.90ms
[E 180222 22:13:14 web:1524] Uncaught exception GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/api/imagecode?codeid=123&pcodeid=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'csrftoken=d5vkJOixfySy6Dz9acL0SDbTrjtFsjvX; sessionid=bivt4n2wqw6y97akihbbv258djo1j4ru', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py", line 23, in get
        name, text, image =captcha.generate_captcha()
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 219, in generate_captcha
        return self.captcha("")
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 205, in captcha
        image = self.text(image, self.fonts, drawings=['warp', 'rotate', 'offset'])
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 128, in text
        for size in font_sizes or (65, 70, 75)])
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 260, in truetype
        return FreeTypeFont(font, size, index, encoding, layout_engine)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 143, in __init__
        self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
    IOError: cannot open resource
[E 180222 22:13:14 web:1946] 500 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 24.93ms
[E 180222 22:13:25 web:1524] Uncaught exception GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/api/imagecode?codeid=123&pcodeid=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'csrftoken=d5vkJOixfySy6Dz9acL0SDbTrjtFsjvX; sessionid=bivt4n2wqw6y97akihbbv258djo1j4ru', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py", line 23, in get
        name, text, image =captcha.generate_captcha()
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 219, in generate_captcha
        return self.captcha("")
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 205, in captcha
        image = self.text(image, self.fonts, drawings=['warp', 'rotate', 'offset'])
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 128, in text
        for size in font_sizes or (65, 70, 75)])
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 260, in truetype
        return FreeTypeFont(font, size, index, encoding, layout_engine)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 143, in __init__
        self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
    IOError: cannot open resource
[E 180222 22:13:25 web:1946] 500 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 23.08ms
[E 180222 22:16:08 torndb:103] Cannot connect to MySQL on 127.0.0.1
    Traceback (most recent call last):
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/torndb.py", line 100, in __init__
        self.reconnect()
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/torndb.py", line 117, in reconnect
        self._db = MySQLdb.connect(**self._db_args)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
        return Connection(*args, **kwargs)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
        super(Connection, self).__init__(*args, **kwargs2)
    OperationalError: (1049, "Unknown database 'ihome'")
[E 180222 22:20:31 web:1524] Uncaught exception GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/api/imagecode?codeid=123&pcodeid=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'csrftoken=d5vkJOixfySy6Dz9acL0SDbTrjtFsjvX; sessionid=bivt4n2wqw6y97akihbbv258djo1j4ru', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py", line 23, in get
        name, text, image =captcha.generate_captcha()
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 219, in generate_captcha
        return self.captcha("")
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 205, in captcha
        image = self.text(image, self.fonts, drawings=['warp', 'rotate', 'offset'])
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 128, in text
        for size in font_sizes or (65, 70, 75)])
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 260, in truetype
        return FreeTypeFont(font, size, index, encoding, layout_engine)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 143, in __init__
        self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
    IOError: cannot open resource
[E 180222 22:20:31 web:1946] 500 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 63.70ms
[E 180222 22:20:32 web:1524] Uncaught exception GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/api/imagecode?codeid=123&pcodeid=', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'zh-CN,zh;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': '127.0.0.1:8000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'csrftoken=d5vkJOixfySy6Dz9acL0SDbTrjtFsjvX; sessionid=bivt4n2wqw6y97akihbbv258djo1j4ru', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py", line 23, in get
        name, text, image =captcha.generate_captcha()
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 219, in generate_captcha
        return self.captcha("")
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 205, in captcha
        image = self.text(image, self.fonts, drawings=['warp', 'rotate', 'offset'])
      File "/home/mypy/02_To_pro/Tornado_Project/utils/captcha/captcha.py", line 128, in text
        for size in font_sizes or (65, 70, 75)])
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 260, in truetype
        return FreeTypeFont(font, size, index, encoding, layout_engine)
      File "/home/wang/.virtualenvs/py2_django/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 143, in __init__
        self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
    IOError: cannot open resource
[E 180222 22:20:32 web:1946] 500 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 22.22ms
[E 180222 22:29:51 VerifyCode:27] 'Application' object has no attribute 'redis'
[I 180222 22:29:51 web:1946] 200 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 4900.02ms
[I 180222 22:35:23 autoreload:204] /home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py modified; restarting server
[E 180222 22:35:38 VerifyCode:27] 'Application' object has no attribute 'redis'
[I 180222 22:35:38 web:1946] 200 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 68.08ms
[E 180222 22:35:51 VerifyCode:27] 'Application' object has no attribute 'redis'
[I 180222 22:35:51 web:1946] 200 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 27.37ms
[E 180222 22:35:52 VerifyCode:27] 'Application' object has no attribute 'redis'
[I 180222 22:35:52 web:1946] 200 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 19.68ms
[E 180222 22:36:00 VerifyCode:27] 'Application' object has no attribute 'redis'
[I 180222 22:36:00 web:1946] 200 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 62.20ms
[E 180222 22:36:00 VerifyCode:27] 'Application' object has no attribute 'redis'
[I 180222 22:36:00 web:1946] 200 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 21.67ms
[I 180222 22:36:05 autoreload:204] /home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py modified; restarting server
[E 180222 22:36:07 VerifyCode:27] 'Application' object has no attribute 'redis'
[I 180222 22:36:07 web:1946] 200 GET /api/imagecode?codeid=123&pcodeid= (127.0.0.1) 63.11ms
[I 180222 22:40:15 autoreload:204] /home/mypy/02_To_pro/Tornado_Project/urls.py modified; restarting server
[I 180222 22:42:17 autoreload:204] /home/mypy/02_To_pro/Tornado_Project/urls.py modified; restarting server
[I 180222 22:53:32 autoreload:204] /home/mypy/02_To_pro/Tornado_Project/urls.py modified; restarting server
[D 180222 23:09:31 Passport:10] debug msg
[I 180222 23:09:31 Passport:11] info msg
[W 180222 23:09:31 Passport:12] warning msg
[E 180222 23:09:31 Passport:13] error msg
[I 180222 23:09:31 web:1946] 304 GET / (127.0.0.1) 3.25ms
[W 180222 23:09:57 web:1946] 404 GET /index/ (127.0.0.1) 4.68ms
[D 180222 23:21:09 Passport:10] debug msg
[I 180222 23:21:09 Passport:11] info msg
[W 180222 23:21:09 Passport:12] warning msg
[E 180222 23:21:09 Passport:13] error msg
[I 180222 23:21:09 web:1946] 304 GET / (127.0.0.1) 3.36ms
[D 180222 23:21:21 Passport:10] debug msg
[I 180222 23:21:21 Passport:11] info msg
[W 180222 23:21:21 Passport:12] warning msg
[E 180222 23:21:21 Passport:13] error msg
[I 180222 23:21:21 web:1946] 304 GET / (127.0.0.1) 3.68ms
[D 180222 23:21:25 Passport:10] debug msg
[I 180222 23:21:25 Passport:11] info msg
[W 180222 23:21:25 Passport:12] warning msg
[E 180222 23:21:25 Passport:13] error msg
[I 180222 23:21:25 web:1946] 304 GET / (127.0.0.1) 1.97ms
[I 180222 23:24:55 autoreload:204] /home/mypy/02_To_pro/Tornado_Project/urls.py modified; restarting server
[I 180222 23:24:57 web:1946] 200 GET / (127.0.0.1) 84.79ms
[I 180222 23:24:57 web:1946] 200 GET /static/plugins/bootstrap/css/bootstrap.min.css (127.0.0.1) 6.05ms
[I 180222 23:24:57 web:1946] 200 GET /static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css (127.0.0.1) 2.54ms
[I 180222 23:24:57 web:1946] 200 GET /static/css/ihome/main.css (127.0.0.1) 4.18ms
[I 180222 23:24:57 web:1946] 200 GET /static/css/ihome/index.css (127.0.0.1) 2.38ms
[I 180222 23:24:57 web:1946] 200 GET /static/plugins/font-awesome/css/font-awesome.min.css (127.0.0.1) 6.99ms
[I 180222 23:24:57 web:1946] 200 GET /static/js/jquery.min.js (127.0.0.1) 3.43ms
[I 180222 23:24:57 web:1946] 200 GET /static/plugins/swiper/css/swiper.min.css (127.0.0.1) 1.83ms
[I 180222 23:24:57 web:1946] 200 GET /static/plugins/bootstrap/js/bootstrap.min.js (127.0.0.1) 4.14ms
[I 180222 23:24:57 web:1946] 200 GET /static/plugins/swiper/js/swiper.jquery.min.js (127.0.0.1) 3.05ms
[I 180222 23:24:58 web:1946] 200 GET /static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js (127.0.0.1) 8.44ms
[I 180222 23:24:58 web:1946] 200 GET /static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js (127.0.0.1) 4.94ms
[I 180222 23:24:58 web:1946] 200 GET /static/js/ihome/index.js (127.0.0.1) 2.58ms
[I 180222 23:24:58 web:1946] 200 GET /static/images/logo@128x59.png (127.0.0.1) 1.66ms
[I 180222 23:24:58 web:1946] 200 GET /static/js/template.js (127.0.0.1) 4.37ms
[I 180222 23:24:58 web:1946] 200 GET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 (127.0.0.1) 6.02ms
[W 180222 23:24:58 web:1946] 404 GET /api/check_login (127.0.0.1) 4.87ms
[W 180222 23:24:58 web:1946] 404 GET /api/house/index (127.0.0.1) 1.46ms
[W 180222 23:25:04 web:1946] 404 GET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map (127.0.0.1) 1.75ms
[I 180222 23:25:05 web:1946] 200 GET /static/plugins/bootstrap/css/bootstrap.min.css.map (127.0.0.1) 17.04ms
[I 180222 23:27:37 web:1946] 304 GET / (127.0.0.1) 3.40ms
[W 180222 23:27:38 web:1946] 404 GET /api/check_login (127.0.0.1) 6.08ms
[W 180222 23:27:38 web:1946] 404 GET /api/house/index (127.0.0.1) 1.87ms
[W 180222 23:27:38 web:1946] 404 GET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map (127.0.0.1) 1.91ms
[I 180222 23:33:42 web:1946] 200 GET /register.html (127.0.0.1) 322.48ms
[I 180222 23:33:43 web:1946] 200 GET /register.html (127.0.0.1) 1.21ms
[I 180222 23:33:46 web:1946] 200 GET /static/css/ihome/register.css (127.0.0.1) 273.24ms
[I 180222 23:33:47 web:1946] 200 GET /static/js/ihome/register.js (127.0.0.1) 1257.93ms
[I 180222 23:40:21 web:1946] 304 GET /register.html (127.0.0.1) 2.96ms
[I 180222 23:40:21 web:1946] 304 GET /static/js/ihome/register.js (127.0.0.1) 1.58ms
[I 180222 23:40:58 web:1946] 304 GET /register.html (127.0.0.1) 2.90ms
[I 180222 23:42:54 web:1946] 304 GET /register.html (127.0.0.1) 2.24ms
[I 180222 23:42:54 web:1946] 200 GET /static/js/ihome/register.js (127.0.0.1) 5.00ms
[E 180222 23:42:55 VerifyCode:27] 'Application' object has no attribute 'redis'
[I 180222 23:42:55 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=48b6d798-9021-4e3a-915f-a04bba4db41c (127.0.0.1) 445.93ms
[E 180222 23:54:32 VerifyCode:27] 'Application' object has no attribute 'redis'
[I 180222 23:54:32 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=4b9f35eb-5ff5-473f-b84c-f1ca2210b63b (127.0.0.1) 41.36ms
[E 180222 23:54:33 VerifyCode:27] 'Application' object has no attribute 'redis'
[I 180222 23:54:33 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=da0befd4-a630-497b-ba96-858a423dabc3 (127.0.0.1) 21.17ms
[I 180223 00:05:02 autoreload:204] /home/mypy/02_To_pro/Tornado_Project/config.py modified; restarting server
[I 180223 00:07:26 web:1946] 304 GET /register.html (127.0.0.1) 36.24ms
[I 180223 00:07:27 web:1946] 304 GET /static/js/ihome/register.js (127.0.0.1) 2.40ms
[I 180223 00:07:27 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=7877b53d-603a-4236-a8c6-6de683bc176d (127.0.0.1) 76.10ms
[E 180223 00:07:29 VerifyCode:27] MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[I 180223 00:07:29 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=86c6f4f1-701a-486c-a002-28fc9fa180f5 (127.0.0.1) 13.13ms
[I 180223 00:09:11 autoreload:204] /home/mypy/02_To_pro/Tornado_Project/handlers/VerifyCode.py modified; restarting server
[E 180223 00:10:10 VerifyCode:27] MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[I 180223 00:10:10 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=e612dacd-1188-4952-a72b-4232cc34aa4e (127.0.0.1) 42.09ms
[E 180223 00:10:22 VerifyCode:27] MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[I 180223 00:10:22 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=c4ad65b9-5e4f-4fe3-b540-2140a5d5a45c (127.0.0.1) 18.25ms
[E 180223 00:10:24 VerifyCode:27] MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[I 180223 00:10:24 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=660e1af0-d114-48cb-8c0f-cfe13c9d1615 (127.0.0.1) 14.90ms
[E 180223 00:10:24 VerifyCode:27] MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[I 180223 00:10:24 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=d9166de1-46da-4139-b7f3-97e1325d57cf (127.0.0.1) 13.70ms
[I 180223 00:10:30 web:1946] 304 GET /register.html (127.0.0.1) 15.14ms
[I 180223 00:10:30 web:1946] 304 GET /static/js/ihome/register.js (127.0.0.1) 4.52ms
[E 180223 00:10:30 VerifyCode:27] MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[I 180223 00:10:30 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=fcb233a5-3131-4b88-80a1-534b866dea37 (127.0.0.1) 25.72ms
[I 180223 00:11:44 web:1946] 304 GET /register.html (127.0.0.1) 3.73ms
[E 180223 00:11:44 VerifyCode:27] MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[I 180223 00:11:44 web:1946] 200 GET /api/imagecode?pcodeid=&codeid=badb19a4-7e73-4e70-82f0-17b5c2ebd3f6 (127.0.0.1) 22.08ms
